### ISSUE TITLE
Hashing results with spaces incorrect

### ISSUE THREAD

**Issue by wolph** [willfarrell/alfred-hash-workflow#2]
Just try:

```
sha1 a b
da23614e02469a0d7c7bd1bdab5c9c474b1904dc
```

Doing the same with the command line sha1sum:

```
# echo -n 'a b' | sha1sum
7dbde93504122a707f849f2c12bdd9de71b41929  -
```

**Comment by willfarrell** [comment]
Very interesting.

To give you an idea, the short version of the code is this:

``` php
$password_algos = [PASSWORD_DEFAULT, PASSWORD_BCRYPT]; // ** Users can add more algos here
$algos = array_merge(hash_algos(), $password_algos);
...
if (in_array($algo, $password_algos)) {
    $hash = password_hash($query, $algo);
} else {
    $hash = hash($algo, $string);
}
```

As you can see nothing to too complicated. This workflow uses the default algos build into php. Odd that the space is not taken into account. hash for `ab` matches up perfectly. Looking into it. 

TODO: Add in unit tests to to compare results with checksums using [sha1sum](https://en.wikipedia.org/wiki/Sha1sum).

**Comment by wolph** [comment]
I think it's actually the Alfred part that's responsible. It probably
doesn't pass along all words.

**Comment by wolph** [comment]
Great, thanks :)

**Comment by willfarrell** [comment]
That's what I thought at first too. It was a bug on my end. New version pushed. Thanks for catching it.
