### ISSUE TITLE
incorrect hashes when used as `hash {query}`

### ISSUE THREAD

**Issue by r-richmond** [willfarrell/alfred-hash-workflow#4]
So I've noticed some strange things happening when I attempt to use `hash {query}`

I think whats happening is that this workflow always ignores the first word in query

1) the example doesn't compute correctly
<img width="564" alt="example_1" src="https://user-images.githubusercontent.com/9246654/30043179-cf4b324c-91aa-11e7-8949-e9ab46113307.png">

1b) but if I use `hash {alg} {query}` it calculates correctly
<img width="576" alt="point_1" src="https://user-images.githubusercontent.com/9246654/30043316-89bdfdee-91ab-11e7-93f9-ce8560d1f0d3.png">

note: I am using Alfred 3 if that matters

**Comment by willfarrell** [comment]
You are right. Just pushed, what I think, to be a fix. Please try it out and let me know. Thanks for reporting it.

**Comment by r-richmond** [comment]
well now I can't get it to work... 

typing `has` shows

<img width="576" alt="1" src="https://user-images.githubusercontent.com/9246654/30044272-0a9fd504-91b1-11e7-84ad-b87d9c4b04de.png">
but when I complete the word `hash`  I get

<img width="571" alt="2" src="https://user-images.githubusercontent.com/9246654/30044298-1d3d8c56-91b1-11e7-9e24-c812a304b650.png">

note: I removed the old workflow and loaded the one from [here](https://github.com/willfarrell/alfred-hash-workflow/blob/master/src/Hash.alfredworkflow)
whereas before I just used the download button from the readme

**Comment by willfarrell** [comment]
Sorry about that. I forgot that Alfred changed where caching is saved, got dir not found. I pushed `v1.5` for you.
