### ISSUE TITLE
MD5 shows before MD4

### ISSUE THREAD

**Issue by r-richmond** [willfarrell/alfred-hash-workflow#5]
Hey @willfarrell, #4 is fixed now but there was one small new issue.

<img width="565" alt="screen shot 2017-09-05 at 7 41 38 am" src="https://user-images.githubusercontent.com/9246654/30067015-761f6576-920e-11e7-9e66-4d3037929812.png">

also your link in the readme for downloading links to an old version(1.3)
`https://raw.github.com/willfarrell/alfred-hash-workflow/master/Hash.alfredworkflow`
should be
`https://raw.github.com/willfarrell/alfred-hash-workflow/master/src/Hash.alfredworkflow` 
& maybe remove the duplicate file `master/Hash.alfredworflow` from the repo? 

(I'm not super familiar with workflows yet so if theres a reason you have it in the repo twice would you care to explain?)

**Comment by willfarrell** [comment]
Just saved it to the wrong folder, updated now. Alfred automatically
changes the order based on past interactions. It likely thinks you're
looking for md5, thus moves it up.

**Comment by r-richmond** [comment]
Ahh didn't realize that feature of Alfred extended to workflows as well. Thanks a ton

p.s. cool project
