### ISSUE TITLE
macOS 12.0+ Monterey no /usr/bin/php

### ISSUE THREAD

**Issue by taoran92** [willfarrell/alfred-hash-workflow#7]
pls notice that.
glhf~

![image](https://user-images.githubusercontent.com/11287509/151304379-c355de45-aeba-4263-aed3-b70689be5f49.png)
 u need to brew it.

**Comment by lrnrzg** [comment]
To Solve this issue, follow these steps:
1.Install Homebrew 
2.Install PHP runtime with Homebrew  `brew install php`
4. Head to setting page of this Alfred workflow, double-click on encode / decode block, and change php to /usr/local/bin/php.

**Comment by taoran92** [comment]
> 

Thanks, I have finished this.
